version: '2'

services:
     
  vtiger-backend:
    build:
      context: .
      dockerfile: ./docker/web/backend/Dockerfile
    environment:
      - VTDB_HOSTNAME=vtiger-db-mysql
      - VTDB_USERNAME=root
      - VTDB_PASSWORD=root
      - VTDB_NAME=vtiger
    volumes:
      - /data/vtiger-backend-bridge/datadir:/data_backend:rw
      - ./web/src:/var/www/html:rw
    depends_on:
      - vtiger-db-mysql
  
  vtiger-db-mysql:
    image: mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vtiger
    volumes:
      - /data/vtiger-mysql-bridge/datadir:/var/lib/mysql
    command: mysqld --sql_mode=""
    
networks:
  default:
    external:
      name: vtiger_net     
